### ISSUE TITLE
Depends on Unix but does not declare it

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [MassD/mongo#22]
For compilation to succeed the library needs to depend on `Unix` but it currently doesn't. This forces users of the library to add the `Unix` dependency themselves.

**Comment by msmfco** [comment]
Thanks for the bug report. 

Would you mind doing a pr with the fix ? 

Thanks

**Comment by Leonidas-from-XIV** [comment]
See #23. Somewhat annoyingly I needed to create s witch with OCaml 4.05 because `bson` is not available for 4.06 and up.
